### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by Disservin** [zborffs/Prometheus#7]
hi,
 if you are looking for some optimizations, you can first create something like `Piece board[64]` plain and simple array which keeps track of all pieces and where they are and update this in makemove and unmake and only initialize at the start for the fen, this way if you want to know what piece is on square x you can simply look it up rather than looping over all pieces.
Also vectors are slow if you remove the vector logic in repetition draw you'll get a small speedup too. Maybe for the movelist too, but I dont know the maximum number of pseudolegal moves... as for totally legal moves most engines use 256 as a maximum.

Happy coding!

**Comment by zborffs** [comment]
Thanks for the ideas!

I like the idea for ```Piece board[64]```. I hadn't thought of that, but that makes a lot of sense. I'll try it.

Yeah, the repetition function is over complicated and pretty wonky, I now realize. Deserves a refactor. I guess you're suggesting just using arrays and looping over those directly? And do that for the ```movelist``` too. 

I'll keep this issue open and update it with data when I get to it.

**Comment by Disservin** [comment]
Yeah though it be hard for the pseudolegal movelist since I have no clue how large it could be... but yeah using arrays and looping over them, as a reference the longest chess game on a professional stage for engines was something like 800 plys (400 moves).
